trigger:
- '*'

stages:
- stage: Echo
  displayName: Echo "hello world"
  jobs:
  - job: EchoJob
    displayName: Echo
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "hello world"
