name: Solar System Workflow 

on: 
    workflow_dispatch: 
    push: 
        branches: 
            - main 
            - 'feature/*'

env: 
    MONGO_URI: 'mongodb+srv://cluster0.d3igiqp.mongodb.net/?retryWrites=true&w=majority'
    MONGO_USERNAME: hatziq 
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs: 
    unit-testing: 
        name: Unit Testing Job 
        strategy: 
            matrix: 
                nodejs_version: [19, 20]
                operating_system: [ubuntu-latest, ubuntu-22.04]
                exclude: 
                    - nodejs_version: 18 
                      operating_system: ubuntu-latest
        runs-on: ${{ matrix.operating_system }}
        steps: 
            - name: Checkout Repo 
              uses: actions/checkout@v4 

            - name: Setup NodeJS v18 
              uses: actions/setup-node@v3 
              with: 
                node-version: ${{ matrix.nodejs_version }}

            - name: Install dependencies 
              run: npm install 

            - name: Unit Testing 
              id: nodejs-unit-testing-step
              run: npm test 

            - name: Archive the Test Result 
              if: steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step == 'success'
              uses: actions/upload-artifact@v3 
              with: 
                name: Mocha-Test-Result
                path: test-results.xml

    code-coverage: 
        name: Code Coverage Job
        runs-on: ubuntu-latest 
        steps: 
        - name: Checkout Repo 
          uses: actions/checkout@v4 
        - name: Setup NodeJS v18 
          uses: actions/setup-node@v3 
          with: 
            node-version: 18 
        - name: Install dependencies 
          run: npm install 

        - name: Check Code Coverage 
          continue-on-error: true 
          run: npm run coverage 

        - name: Archive the Coverage Result 
          uses: actions/upload-artifact@v3 
          with: 
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5        
        